[technote]
id = "SQR-001"
series_id = "SQR"
canonical_url = "https://sqr-001.lsst.io"
github_url = "https://github.com/lsst-sqre/sqr-001"
github_default_branch = "main"
date_created = "2023-10-31T22:14:27Z"

[[technote.authors]]
name = { name = "Frossie Economou" }
# orcid = "https://orcid.org/..."
# affiliations = [
#     { name = "Rubin Observatory", ror = "https://ror.org/048g3cy84" }
# ]

[technote.status]
state = "draft"
